name: Publish Pending Posts
on:
  schedule:
    - cron: '*/15 * * * *' # каждые 15 минут
  workflow_dispatch:

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Run publisher script
        env:
          BOT_TOKEN: ${{ secrets.BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          CHANNEL_ID: ${{ secrets.CHANNEL_ID }}
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: python publisher.py
